name: Download and Unzip

on:
  workflow_dispatch:

jobs:
  download_and_unzip:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download zip file
        run: Invoke-WebRequest -Uri "https://repo-doc-onlyoffice-com.s3.eu-west-1.amazonaws.com/windows/docspace/win.zip" -OutFile "file.zip"

      - name: Unzip file to install/win
        run: Expand-Archive -Path "file.zip" -DestinationPath "${{ github.workspace }}\\install\\win"

      - name: Display extracted files
        run: dir "${{ github.workspace }}\\install\\win"

      - name: Run PowerShell Script
        run: |
         $env:DOCUMENT_SERVER_VERSION_EE = 'latest'
         $env:DOCUMENT_SERVER_VERSION_CE = 'latest'
         & "${{ github.workspace }}\install\win\build-download-prereq.ps1"
        shell: pwsh

      - name: Display extracted files
        run: dir "${{ github.workspace }}\\install\\win\\redist"

      - name: Build AIP
        uses: caphyon/advinst-github-action@v2.0
        with:
          advinst-version: '20.7.1'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}\install\win\OpenResty.aip
      - name: Build AIP
        uses: caphyon/advinst-github-action@v2.0  
        with:
          advinst-version: '20.7.1'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}\install\win\OpenSearch.aip
      - name: Build AIP
        uses: caphyon/advinst-github-action@v2.0  
        with:
          advinst-version: '20.7.1'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}\install\win\OpenSearchStack.aip
      - name: Build AIP
        uses: caphyon/advinst-github-action@v2.0  
        with:
          advinst-version: '20.7.1'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}\install\win\DocSpace.aip
          
      
      - name: Display publsih
        run: dir "${{ github.workspace }}\\install\\win\publish"
